---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  html_notebook: default
---


```{r}
peoplefile <- read.delim("D:/Data Mining/Practicals/people.txt",sep=" ")
peoplefile
```
```{r}
library(sqldf)
```

```{r}
totalRows <- nrow(peoplefile)
paste(totalRows)
```
```{r}
query1 <- "SELECT
                            AGE,
                            AGEGROUP,
                            HEIGHT,
                            STATUS,
                            YEARSMARRIED
                        FROM
                            peoplefile
                        WHERE
                            AGE >=0 AND AGE <=150"
sqldf(query1)
rule1Voilated <- totalRows - nrow(sqldf(query1))
```
```{r}
#RULE SET 2
query2 <- "SELECT
                    AGE,
                    AGEGROUP,
                    HEIGHT,
                    STATUS,
                    YEARSMARRIED
                FROM
                    peoplefile
                WHERE
                    AGE > YEARSMARRIED"
sqldf(query2)
rule2Voilated <- totalRows - nrow(sqldf(query2))
```


```{r}
#RULE SET 3
query3 <- "SELECT
                  AGE,
                  AGEGROUP,
                  HEIGHT,
                  STATUS,
                  YEARSMARRIED
              FROM
                  peoplefile
              WHERE
                      STATUS='married' OR STATUS='single'OR STATUS='widowed' "
sqldf(query3)
rule3Voilated <- totalRows - nrow(sqldf(query3))
```


```{r}
#RULE SET 4
query4 <- "SELECT
                AGE,
                AGEGROUP,
                HEIGHT,
                STATUS,
                YEARSMARRIED
          FROM
                peoplefile
          WHERE
                AGE < 18 AND AGEGROUP = 'child' OR
                AGE BETWEEN 18 AND 65 AND AGEGROUP = 'adult' OR 
                AGE > 65 AND AGEGROUP = 'elderly' "
sqldf(query4)
rule4Voilated <- totalRows - nrow(sqldf(query4))
```
```{r}
cat("Rule Set Voilations Summary \n",
    "RuleSet 1 :",rule1Voilated,"\n",
    "RuleSet 2 :",rule2Voilated,"\n",
    "RuleSet 3 :",rule3Voilated,"\n",
    "RuleSet 4 :",rule4Voilated,"\n")
```
```{r}

totalVoilations <- as.integer(c(rule1Voilated,rule2Voilated,rule3Voilated,rule4Voilated))
plot(totalVoilations,xlab = "Rule",ylab = "Number of Times Violated")
barplot(totalVoilations,xlab="Rules",ylab = "Number of Times Violated",names.arg = c("Rule1","Rule 2","Rule 3","Rule 4"))
```